name: CI

on:
  push:
    branches-ignore: [master]
  pull_request:
    branches: ['*']
  schedule:
    - cron: '20 6 * * *'

jobs:
  tests:
    timeout-minutes: 20 # default is 6 hours!
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        rust: [stable]
        include:
          - os: ubuntu-latest
            rust: beta
          - os: ubuntu-latest
            rust: nightly
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - run: bash ci/install-rust.sh ${{ matrix.rust }}
      # Temporary workaround until Package Control 4 works
      # https://github.com/wbond/package_control/issues/1612
      - name: Fix macOS OpenSSL
        if: matrix.os == 'macos-latest'
        run: brew unlink openssl
      - uses: SublimeText/UnitTesting/actions/setup@v1
        with:
          package-name: Rust Enhanced
      - uses: SublimeText/UnitTesting/actions/run-syntax-tests@v1
      - uses: SublimeText/UnitTesting/actions/run-tests@v1
